large_text = """The first commercially successful engine that could transmit continuous power to a machine was the atmospheric engine, invented by Thomas Newcomen around 1712.[b][17] It improved on Savery's steam pump, using a piston as proposed by Papin. Newcomen's engine was relatively inefficient, and mostly used for pumping water. It worked by creating a partial vacuum by condensing steam under a piston within a cylinder. It was employed for draining mine workings at depths originally impractical using traditional means, and for providing reusable water for driving waterwheels at factories sited away from a suitable "head". Water that passed over the wheel was pumped up into a storage reservoir above the wheel.[18][19] In 1780 James Pickard patented the use of a flywheel and crankshaft to provide rotative motion from an improved Newcomen engine.[20]
In 1720, Jacob Leupold described a two-cylinder high-pressure steam engine.[21] The invention was published in his major work "Theatri Machinarum Hydraulicarum".[22] The engine used two heavy pistons to provide motion to a water pump. Each piston was raised by the steam pressure and returned to its original position by gravity. The two pistons shared a common four-way rotary valve connected directly to a steam boiler.
Early Watt pumping engine
The next major step occurred when James Watt developed (1763–1775) an improved version of Newcomen's engine, with a separate condenser. Boulton and Watt's early engines used half as much coal as John Smeaton's improved version of Newcomen's.[23] Newcomen's and Watt's early engines were "atmospheric". They were powered by air pressure pushing a piston into the partial vacuum generated by condensing steam, instead of the pressure of expanding steam. The engine cylinders had to be large because the only usable force acting on them was atmospheric pressure.[18][24]
Watt developed his engine further, modifying it to provide a rotary motion suitable for driving machinery. This enabled factories to be sited away from rivers, and accelerated the pace of the Industrial Revolution.[24][18][25]"""

# переводим всё в один регистр
large_text = large_text.lower()
# разбиваем на слова
words = large_text.split()
print(f'Символов: {len(large_text)}, Слов: {len(words)}')
print(words)
print(type(words))

print(words.count('engine'))

alteration_signs = '.,[]1234567890;:!?-()'
preprocessed_words = list()
# pre-processing каждого слова
for i, word in enumerate(words):
    word = word.strip(alteration_signs)
    # менять список по ходу его итерации - нехорошо, это антипаттерн (так лучше не делать)
    # пословица "пилить сук на котором сидишь"
    words[i] = word
    # лучше создать новый список и туда сохранять
    preprocessed_words.append(word)
print(preprocessed_words)
print(words)
word_counts = list()
for word in preprocessed_words:
     x = preprocessed_words.count(word)
     print(f'Слово {word} встречается {x} раз')
     word_counts.append(x)

print(word_counts)
print(max(word_counts))
print(min(word_counts))
# сортируем популяцию слов по убыванию (от большего к меньшему)
# оказывается, много дубликатов...
print(sorted(word_counts, reverse=True))

# убираем дубликаты
unique_word_counts = set(word_counts)
# сортируем еще раз - сет нарушает порядок значений
sorted_unique_word_counts = sorted(unique_word_counts, reverse=True)
# выводим топ 5 :)
print(sorted_unique_word_counts[:5])

# пример работы с множеством (будет продолжение и разбор дальше)
# убрал дубликаты
x = set([5, 5, 4, 5, 4, 3, 1, 4, 3, 2])
print(x)

