import pprint

large_text = """The first commercially successful engine that could transmit continuous power to a machine was the atmospheric engine, invented by Thomas Newcomen around 1712.[b][17] It improved on Savery's steam pump, using a piston as proposed by Papin. Newcomen's engine was relatively inefficient, and mostly used for pumping water. It worked by creating a partial vacuum by condensing steam under a piston within a cylinder. It was employed for draining mine workings at depths originally impractical using traditional means, and for providing reusable water for driving waterwheels at factories sited away from a suitable "head". Water that passed over the wheel was pumped up into a storage reservoir above the wheel.[18][19] In 1780 James Pickard patented the use of a flywheel and crankshaft to provide rotative motion from an improved Newcomen engine.[20]
In 1720, Jacob Leupold described a two-cylinder high-pressure steam engine.[21] The invention was published in his major work "Theatri Machinarum Hydraulicarum".[22] The engine used two heavy pistons to provide motion to a water pump. Each piston was raised by the steam pressure and returned to its original position by gravity. The two pistons shared a common four-way rotary valve connected directly to a steam boiler.
Early Watt pumping engine
The next major step occurred when James Watt developed (1763–1775) an improved version of Newcomen's engine, with a separate condenser. Boulton and Watt's early engines used half as much coal as John Smeaton's improved version of Newcomen's.[23] Newcomen's and Watt's early engines were "atmospheric". They were powered by air pressure pushing a piston into the partial vacuum generated by condensing steam, instead of the pressure of expanding steam. The engine cylinders had to be large because the only usable force acting on them was atmospheric pressure.[18][24]
Watt developed his engine further, modifying it to provide a rotary motion suitable for driving machinery. This enabled factories to be sited away from rivers, and accelerated the pace of the Industrial Revolution.[24][18][25]"""

top_n = 5

alteration_signs = '.,"[]1234567890;:!?-–()'
stop_words = {'', 'the', 'a', 'an', 'by', 'was', 'and', 'of', 'for', 'in', 'on', 'it', 'to', 'as'}
# переводим всё в один регистр
large_text = large_text.lower()
# разбиваем на слова
words = large_text.split()
print(f'Символов: {len(large_text)}, Слов: {len(words)}')
print(words)
print(type(words))

# делаем словарь
words_metadata = dict()
for word in words:
    word = word.strip(alteration_signs)
    if word in stop_words:
        continue
    if word in words_metadata:
        # одинаковые команды
        # words_population[word] = words_population[word] + 1
        # встречаем это слово в n+1 раз
        words_metadata[word]['population'] += 1
    else:
        # встречаем это слово впервые
        words_metadata[word] = {
            'population': 1,
            'len': len(word),
            'first_letter': word[0]
        }

print(words_metadata)

words_metadata_list = list(words_metadata.items())

# сортируем по популярности
words_metadata_list.sort(key=lambda x: x[1]['population'], reverse=True)
print(f"Наиболее популярные {top_n} слов")
pprint.pprint(words_metadata_list[:top_n])
print(f"Наименее популярные {top_n} слов")
pprint.pprint(words_metadata_list[-top_n:][::-1])

# сортируем по длине слова
words_metadata_list.sort(key=lambda x: x[1]['len'], reverse=True)
print(f"Самые длинные {top_n} слов")
pprint.pprint(words_metadata_list[:top_n])
print(f"Самые короткие {top_n} слов")
pprint.pprint(words_metadata_list[-top_n:][::-1])


def select_only_f(x):
    return x[1]['first_letter'] == 'f'


print('Слова которые начинаются на f (используя обычную функцию)')
pprint.pprint(list(filter(select_only_f, words_metadata_list)))
print('Слова которые начинаются на f (используя лямбда функцию)')
pprint.pprint(list(filter(lambda x: x[1]['first_letter'] == 'f', words_metadata_list)))


print(words_metadata['pressure'])